// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: account.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (id, email, password, first_name, last_name, profile_picture, is_administrator)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, email, password, first_name, last_name, profile_picture, is_administrator, active
`

type CreateAccountParams struct {
	ID              uuid.UUID
	Email           string
	Password        string
	FirstName       sql.NullString
	LastName        sql.NullString
	ProfilePicture  sql.NullString
	IsAdministrator bool
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.ProfilePicture,
		arg.IsAdministrator,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePicture,
		&i.IsAdministrator,
		&i.Active,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, created_at, updated_at, email, password, first_name, last_name, profile_picture, is_administrator, active FROM account
WHERE email=$1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePicture,
		&i.IsAdministrator,
		&i.Active,
	)
	return i, err
}

const getAccountIdByEmail = `-- name: GetAccountIdByEmail :one
SELECT id FROM account
WHERE email=$1 AND active=TRUE
`

func (q *Queries) GetAccountIdByEmail(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getAccountIdByEmail, email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getActiveAccountById = `-- name: GetActiveAccountById :one
SELECT id, created_at, updated_at, email, password, first_name, last_name, profile_picture, is_administrator, active FROM account
WHERE id=$1 and active=TRUE
`

func (q *Queries) GetActiveAccountById(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getActiveAccountById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePicture,
		&i.IsAdministrator,
		&i.Active,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE account 
SET first_name = $1,
    last_name = $2,
    profile_picture = coalesce($3, profile_picture)
WHERE id=$4
RETURNING id, created_at, updated_at, email, password, first_name, last_name, profile_picture, is_administrator, active
`

type UpdateAccountParams struct {
	FirstName      sql.NullString
	LastName       sql.NullString
	ProfilePicture sql.NullString
	ID             uuid.UUID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.FirstName,
		arg.LastName,
		arg.ProfilePicture,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePicture,
		&i.IsAdministrator,
		&i.Active,
	)
	return i, err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :one
UPDATE account 
SET password = $1
WHERE id=$2
RETURNING id, created_at, updated_at, email, password, first_name, last_name, profile_picture, is_administrator, active
`

type UpdateAccountPasswordParams struct {
	Password string
	ID       uuid.UUID
}

func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccountPassword, arg.Password, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePicture,
		&i.IsAdministrator,
		&i.Active,
	)
	return i, err
}
