# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: go_htmx
      POSTGRES_PASSWORD: DevPassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:7.7
    environment:
      PGADMIN_DEFAULT_EMAIL: go_htmx@example.com
      PGADMIN_DEFAULT_PASSWORD: DevPassword
    ports:
      - 8000:80

  redis:
    image: redis/redis-stack:7.2.0-v3
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
      - 8001:8001

volumes:
  postgres-data:
  redis-data:
